<a href="https://colab.research.google.com/github/99ashmeet/99ashmeet.github.io/blob/master/deepfake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
!cp /content/drive/MyDrive/minor_project/deepfake_database.zip /content/deepFake_detection_algo

In [3]:
cd deepFake_detection_algo/

/content/deepFake_detection_algo


In [4]:
!7z x deepfake_database.zip


7-Zip [64] 16.02 : Copyright (c) 1999-2016 Igor Pavlov : 2016-05-21
p7zip Version 16.02 (locale=en_US.UTF-8,Utf16=on,HugeFiles=on,64 bits,2 CPUs AMD EPYC 7B12 (830F10),ASM,AES-NI)

Scanning the drive for archives:
  0M Scan         1 file, 192901191 bytes (184 MiB)

Extracting archive: deepfake_database.zip
 21% 4096 Open              --
Path = deepfake_database.zip
Type = zip
Physical Size = 192901191

  0%      4% 525 - deepfake_database/deepfake_database/train:test/df/df00520.jpg                                                                          6% 860 - deepfake_database/deepfake_database/train:test/df/df00855.jpg                                                                        

In [19]:
cd /content/deepFake_detection_algo/deepfake_database/deepfake_database/train:test/fake

/content/deepFake_detection_algo/deepfake_database/deepfake_database/train:test/fake


In [21]:
cd /content/deepFake_detection_algo/deepfake_database/deepfake_database

/content/deepFake_detection_algo/deepfake_database/deepfake_database


In [22]:
!cp /content/deepFake_detection_algo/deepfake_database/deepfake_database/train:test/fake/* /content/deepFake_detection_algo/deepfake_database/deepfake_database/train:test/real/* /content/deepFake_detection_algo/deepfake_database/deepfake_database/validation/fake/* /content/deepFake_detection_algo/deepfake_database/deepfake_database/validation/real/* /content/deepFake_detection_algo/deepfake_database/deepfake_database/dataset 

In [23]:
!cp /content/deepFake_detection_algo/deepfake_database/deepfake_database/validation/fake/* /content/deepFake_detection_algo/deepfake_database/deepfake_database/train:test/fake
!cp /content/deepFake_detection_algo/deepfake_database/deepfake_database/validation/real/* /content/deepFake_detection_algo/deepfake_database/deepfake_database/train:test/real

In [24]:
!mv /content/deepFake_detection_algo/deepfake_database/deepfake_database/train:test/* /content/deepFake_detection_algo/deepfakedetection 

In [25]:
cd /content/deepFake_detection_algo

/content/deepFake_detection_algo


In [34]:
import cv2, csv, os, shutil
import numpy as np
from PIL import Image
path = os.getcwd()

dataset_deepfakedetection = path + '/deepfakedetection'
datasets = [dataset_deepfakedetection]
output_folder = path + '/images/'
with open(output_folder + 'images.csv', 'a') as csv_file:
  filewriter = csv.writer(csv_file, delimiter=',')
  filewriter.writerow(['image_id','fake','original_dataset'])
for dataset in datasets:
  for real_image in os.listdir(dataset + '/real'):
    if real_image.endswith('.jpg'):

      shutil.move(dataset + '/real/' + real_image, output_folder + real_image)
      with open(output_folder + 'images.csv', 'a') as csv_file:
        filewriter = csv.writer(csv_file, delimiter=',')
        filewriter.writerow([real_image, 0, dataset.rsplit('/', 1)[1]])
    else:
      continue
  for fake_image in os.listdir(dataset + '/fake'):
    if fake_image.endswith('.jpg'):
     
      shutil.move(dataset + '/fake/' + fake_image, output_folder + fake_image)
      with open(output_folder + 'images.csv', 'a') as csv_file:
        filewriter = csv.writer(csv_file, delimiter=',')
        filewriter.writerow([fake_image, 1, dataset.rsplit('/', 1)[1]])
    else:
      continue

print("Files have been successfully moved into the output folder and all information put into a CSV file.")

Files have been successfully moved into the output folder and all information put into a CSV file.


In [ ]:
import pandas as pd 
df=pd.read_csv('images/images.csv')
df = df.sample(frac=1)

In [35]:
cd /content/deepFake_detection_algo/images

/content/deepFake_detection_algo/images


In [43]:
import pandas as pd 
df=pd.read_csv('images.csv')
df = df.sample(frac=1)

In [44]:
df_1 = df.iloc[:15564,:] 
df_2 = df.iloc[15564:17510,:] 
df_3 = df.iloc[17510:,:]

df_1.to_csv('../train_split.csv', index=False) 
df_2.to_csv('../val_split.csv', index=False) 
df_3.to_csv('../test_split.csv', index=False) 

In [48]:
!cp /content/deepFake_detection_algo/splits/* /content/drive/MyDrive/minor_project/splits

In [17]:
# x_train= x_train.reshape(60000,28,28,1)
# x_test= x_test.reshape(10000,28,28,1)
import pandas as  pd
import numpy as np
import cv2

def makeDataSet(file_csv):

  x = []
  y = []

  for i in file_csv.index:

    if(file_csv['image_id'][i]=="image_id"):
      continue;
  
    img_address = "images/" + str(file_csv['image_id'][i]);

    img = cv2.imread(img_address)
    img = cv2.resize(img,(256,256))

    img_array = np.array(img)

    x.append(img_array)
    y.append(file_csv['fake'][i])  
  
  x = np.array(x)
  y = np.array(y)

  return x,y

In [18]:
x_train,y_train = makeDataSet(pd.read_csv('/content/deepFake_detection_algo/splits/train_split.csv'))
x_validate,y_validate = makeDataSet(pd.read_csv('/content/deepFake_detection_algo/splits/val_split.csv'))
x_test,y_test = makeDataSet(pd.read_csv('/content/deepFake_detection_algo/splits/test_split.csv'))

In [14]:
cd /content/deepFake_detection_algo

/content/deepFake_detection_algo


In [19]:
print(x_train.shape)
print(y_train.shape)
print(x_validate.shape)
print(y_validate.shape)
print(x_test.shape)
print(y_test.shape)

(15559, 256, 256, 3)
(15559,)
(1945, 256, 256, 3)
(1945,)
(1952, 256, 256, 3)
(1952,)


In [14]:
# from PIL import Image 
# import numpy 
  
  
# img= Image.open("df00000.jpg") 
# np_img = numpy.array(img) 
  
# print(np_img.shape)

(462, 462, 3)


In [20]:
# print(np_img)

[[[229 226 255]
  [229 226 255]
  [229 226 255]
  ...
  [227 227 255]
  [227 227 255]
  [227 227 255]]

 [[229 226 255]
  [229 226 255]
  [229 226 255]
  ...
  [227 227 255]
  [227 227 255]
  [227 227 255]]

 [[229 226 255]
  [229 226 255]
  [229 226 255]
  ...
  [227 227 255]
  [227 227 255]
  [227 227 255]]

 ...

 [[ 19   9   7]
  [ 19   9   7]
  [ 18   8   6]
  ...
  [  7   1   3]
  [  7   1   3]
  [  7   1   3]]

 [[ 19   9   7]
  [ 19   9   7]
  [ 19   9   7]
  ...
  [  7   1   3]
  [  7   1   3]
  [  7   1   3]]

 [[ 20  10   8]
  [ 20  10   8]
  [ 19   9   7]
  ...
  [  9   0   3]
  [  9   0   3]
  [  9   0   3]]]


In [13]:
# type(df00000.jpg)

NameError: ignored

In [20]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Conv2D
from keras.layers import MaxPool2D
from keras.layers import Dropout
from keras.layers import Flatten
import numpy as np

In [21]:
model= Sequential()

In [ ]:
cnn1= Conv2D(filters=256, kernel_size=(5,5), strides=(1,1), padding= "SAME",activation="relu", use_bias=True, input_shape=(256,256,3))
model.add(cnn1)
model.add(MaxPool2D(pool_size=(2,2), strides=(1,1)))
model.add(Conv2D(filters=128, kernel_size=(5,5), strides=(1,1), padding= "SAME",activation="relu", use_bias=True))
model.add(MaxPool2D(pool_size=(2,2), strides=(1,1)))
model.add(Conv2D(filters=64, kernel_size=(5,5), strides=(1,1), padding= "SAME",activation="relu", use_bias=True))
model.add(MaxPool2D(pool_size=(2,2), strides=(1,1)))
model.add(Conv2D(filters=32, kernel_size=(5,5), strides=(1,1), padding= "SAME",activation="relu", use_bias=True))
model.add(MaxPool2D(pool_size=(2,2), strides=(1,1)))
model.add(Dropout(rate=0.5))
model.add(Flatten())
model.add(Dense(units=1024, activation="relu"))
model.add(Dense(units=1,activation="sigmoid"))

In [ ]:
model.fit(x_train,y_train, epochs=10, batch_size= 1000, validation_data=(x_validate,y_validate))

In [ ]:
evaluated= model.evaluate(x_test,y_test)

In [ ]:
print('Test loss:', evaluated[0])
print('Test accuracy:', evaluated[1])